spring.application.name=ravania
spring.datasource.url=jdbc:mariadb://localhost:3306/ravania
spring.datasource.username=admin
spring.datasource.password=testes1234
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jackson.deserialization.accept-empty-string-as-null-object=true